### ISSUE TITLE
Missing PyPi v0.5.5

### ISSUE THREAD

**Issue by fmigneault** [bird-house/twitcher#101]
The version is missing on PyPi although it exists on Dockerhub: 
https://pypi.org/project/pyramid-twitcher/#history
https://hub.docker.com/r/birdhouse/twitcher/tags?page=1&ordering=last_updated

I'm not sure on the release procedure for pypi. Can it be deployed?

**Comment by cehbrecht** [comment]
done:
https://pypi.org/project/pyramid-twitcher/0.5.5/
