### ISSUE TITLE
add job monitoring middleware component

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/twitcher#21]
... to have common job monitoring component in front of the wps service when accessed by several clients.

**Comment by fmigneault** [comment]
Maybe you could consider using https://github.com/crim-ca/weaver, which already supports WPS 1.0, 2.0 and REST interfaces, as well as single app vs workflow execution with same REST JSON /jobs routes.

Would also address #24, #38, #44

Currently working on bringing back our Twitcher-specific REST/JSON changes on top of your master.

**Comment by cehbrecht** [comment]
@fmigneault is weaver meant to be a replacement of twitcher or is weaver a middleware extension? I'm currently cleaning twitcher up to get the secured-wps-proxy functionality into our copernicus deployment.

**Comment by fmigneault** [comment]
@cehbrecht 
Everything related to the REST API interface we attempted adding to Twitcher in the pass is included in Weaver instead.
It also adds extra features like support for 'wrapping' older WPS1.0 processes to allow WPS-REST-like interaction such as job submission with JSON and workflow jobs execution on remote servers.
Weaver doesn't do anything related to token handling or permission verification, just the core process execution part.
We are planing to place Weaver behind Twitcher proxy using the Magpie adapter.

**Comment by cehbrecht** [comment]
will be part of [weaver](https://github.com/crim-ca/weaver).
