### ISSUE TITLE
Swagger API on top of WPS service?

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/twitcher#41]
... client code can be generated by swagger-codegen to have a simplified usage of WPS service for example in a Jupyter notebook. 

See: https://github.com/bird-house/bird-house.github.io/issues/19

Infos about swagger: https://medium.com/runscope/openapi-swagger-resource-list-for-api-developers-9f6d769d9c9d

**Comment by huard** [comment]
I suggest we close this and focus on the python client for now.

**Comment by tomLandry** [comment]
I would have changed the version instead of closing. We have concording work to do at OGC. Even more so as the issue was written with an interrogration point!

**Comment by huard** [comment]
Feel free to reopen it, I just don't want to crowd our intellectual bandwidth. My take was that the marginal benefits of the swagger client codegen just got smaller because there is a proposed python implementation.

**Comment by tomLandry** [comment]
For sure, bandwith is pretty scarce these days! I think it's still worthwile to keep the whole OpenAPI - Swagger discussion alive but on the back-burner at low intensity. It was a very important topic in the evolution of OWS presented by the Open Architecture Board of OGC (the thinking heads). Expect some material in the upcoming engineering reports, for instance. So to me, very important but not urgent.
