### ISSUE TITLE
Making OGC TB-14 Twitcher code available

### ISSUE THREAD

**Issue by tomLandry** [bird-house/twitcher#46]
As discussed today, CRIM's version of Twitcher has heavily increased capabilities and roles compared to a Proxy. This issue is to recapitulate the major changes and establish how to reintegrate the desired changes into the Birdhouse upstream.

At the same time, there is a demand from ESA and NRCan to see this code open sourced.

**Comment by cehbrecht** [comment]
I have collected issues for the birdhouse/twitcher clean up. We need to find a way to bring our "twitcher ogc/middleware" efforts together. We might also like to have a new combined "twitcher", maybe based on flask. Currently I try to get the "birdhouse/twitcher" ready for the Copernicus requirements.

**Comment by tomLandry** [comment]
Excellent. David Byrns and Francis worked a bit on the design. We will most probably split the TEP part (Execution Management System / Application Deployment & Execution System) from the OGC work, into a new component. I'm sending you some diagrams. That will make it much easier to do a PR on Twitcher and integrate other improvements and corrections.

**Comment by fmigneault** [comment]
resolved according to https://github.com/bird-house/twitcher/issues/21#issuecomment-494792044 via https://github.com/crim-ca/weaver
