### ISSUE TITLE
Support HTTPS for proxy ows (wps) services

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/twitcher#48]
The current twitcher implementation fails for https services with self-signed certificates. 

There is already a patch available which needs to be integrated:
https://github.com/Ouranosinc/twitcher/commit/b42e052

See also issue #46.

**Comment by cehbrecht** [comment]
@tlvu @huard  I try to integrate the patch from ouranos.

**Comment by tlvu** [comment]
@cehbrecht FYI, I tried the patch from Francis in a full PAVICS deployment and it works.

**Comment by cehbrecht** [comment]
@tlvu @huard what do you think about PR #55?

**Comment by huard** [comment]
I'm out of my depth, but looks good.

**Comment by cehbrecht** [comment]
Well, I merge ... we can figure out later.

**Comment by cehbrecht** [comment]
fixed by PR #55.

**Comment by tlvu** [comment]
@cehbrecht oops sorry, I didn't realized you wanted a PR review since I was not in the reviewer list.  At my previous workplace, we were explicit in requesting review by adding the intended person(s) to the reviewers list.

**Comment by tlvu** [comment]
@cehbrecht wow patch is so different than the original patch !  Don't think I would be able to review either.  Fun time ahead for merging the difference between this version of twitcher and the version in ouranosinc :(

**Comment by cehbrecht** [comment]
@tlvu in the birdhouse patch the `ssl_verify` is a parameter in the service registry, so you can decide for each WPS service.

**Comment by tlvu** [comment]
@cehbrecht ah nice!  Disabling SSL certificate verification only for those WPS services that are behind self-signed.
