### ISSUE TITLE
replace mongodb by sqlalchemy (sqlite, postgres)?

### ISSUE THREAD

**Issue by cehbrecht** [bird-house/twitcher#51]
... would be at least one component (DB) less to maintain. We need postgres already for pywps.

See also #46.

**Comment by fmigneault** [comment]
During the OGC work, I added a "DatabaseInterface" that targeted the various Twitcher stores using MongoDB/Postgress variants defined by config with `twitcher.db_factory = mongodb | postgres`.
The postgres interface is not 100% finished, but basic setup of connection engine and transaction should be good to go.
I can leave it in the #46 cleanup if you'd like.

**Comment by cehbrecht** [comment]
> I can leave it in the #46 cleanup if you'd like.

@fmigneault yes, we can keep it. Do you think we should skip mongodb? We already need postgres and it is more trouble to maintain two database systems.

**Comment by fmigneault** [comment]
@cehbrecht most of my implementations use mongodb at the moment since it was easier for us to dump some inputs as json. If everything is migrated to postgres with their models, yes we could only keep it and remove mongo.

**Comment by cehbrecht** [comment]
fixed by PR #64.
