### ISSUE TITLE
Twitcher unable to handle large http POST?

### ISSUE THREAD

**Issue by tlvu** [bird-house/twitcher#80]
We have an issue with the Ouranos fork of twitcher, which I think, I am entirely guessing here, is related to the large size of the http POST operation.  See problem description here https://github.com/Ouranosinc/Magpie/issues/189.

I was wondering if bird-house twitcher has ever had the same problem or if you can offer any debugging advice related to twitcher in general, thanks.

**Comment by cehbrecht** [comment]
Following the discussion on https://github.com/Ouranosinc/Magpie/issues/189
you already found a solution.

I had never a problem with post requests ... but probably they were not that large.

The `client_max_body_size` can be made configurable in the ansible deployment for nginx/twitcher.
https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

**Comment by tlvu** [comment]
Found a solution in Ouranosinc/Magpie#189 for our current version of twitcher.  From that issue, apparently the latest twitcher do not have nginx anymore so this issue should not apply to latest twitcher anymore, closing.
