### ISSUE TITLE
DOI integration

### ISSUE THREAD

**Issue by Zeitsperre** [bird-house/twitcher#90]
The Zenodo DOI is now set up with twitcher! 

In order to get the ball rolling, there needs to be a tagged release at some point. Once that has happened, we can add the DOI badge to the README.

**Comment by tomLandry** [comment]
Woah that sounds like pretty important news. I wasn't aware that DOI work was ongoing. @dbyrns please note https://zenodo.org/ as this falls into DACCS WP2.2.

**Comment by Zeitsperre** [comment]
@tomLandry This was one of the issue raised in the last meeting. Eventually we want to propose part of the Bird-house infrastructure to [JOSS](https://joss.theoj.org/) and the project as a whole to a traditional open access journal. Getting a DOI is step one.

**Comment by tomLandry** [comment]
Ah ok, I got this the other way around then. Sorry I wasn't aware of that. I thought you started experimenting on DOIs attribution for climate data hosted in PAVICS/DACCS catalogs. Which begs the question, can Zenodo help for this?

**Comment by Zeitsperre** [comment]
Good question. I just noted that there are presentations tagged with DOIs. Worth investigating.

**Comment by Zeitsperre** [comment]
I don't think Zenodo can do this at the scale we need (+tens of thousands of data files) but I think [DataCite](https://datacite.org/index.html) might be an (non-free) option.

**Comment by huard** [comment]
See synapse.org. It's a place to archive digital assets which can mint DOIs.

**Comment by tomLandry** [comment]
I'm preparing the high level planification for DACCS. I don't think we'll scramble on this in 2019, but we might do a quick review of the state of the art. Maybe some experiments in TR1-2020. I would start more seriously on this TR2-20202. Please tell me if you have more urgency on DOI support for climate assets.

**Comment by fmigneault** [comment]
Note that if it is in order to provide references for DACCS/birdhouse-deploy stack, Twitcher 0.5.x is used.
The DOI points explicitly to 0.6.0 that is not actually used at the moment.

**Comment by fmigneault** [comment]
@Zeitsperre 
I just read about the following feature in Github. 
Might be of interest for referencing. 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files
